USE MINTCLASSICS;

-- -------------------------------------------------------------------------------------------------------------
-- EXPLORATORY DATA ANALYSIS --
-- -------------------------------------------------------------------------------------------------------------

-- I --
-- INVENTORY UNITS PER PRODUCTLINE PER WAREHOUSE
SELECT DISTINCT W.WAREHOUSENAME, P.PRODUCTLINE, SUM(P.QUANTITYINSTOCK) AS PRODSTOCK 
FROM PRODUCTS P, WAREHOUSES W 
WHERE W.WAREHOUSECODE=P.WAREHOUSECODE 
GROUP BY P.PRODUCTLINE, W.WAREHOUSENAME ORDER BY W.WAREHOUSENAME, P.PRODUCTLINE;

-- INVENTORY UNITS PER WAREHOUSE
SELECT DISTINCT W.WAREHOUSENAME, SUM(P.QUANTITYINSTOCK) AS PRODSTOCK 
FROM WAREHOUSES W, PRODUCTS P 
WHERE W.WAREHOUSECODE=P.WAREHOUSECODE 
GROUP BY W.WAREHOUSENAME;

-- II --
-- INVENTORY UNITS AND REVENUE PER PRODUCT
SELECT DISTINCT P.PRODUCTNAME, SUM(P.QUANTITYINSTOCK) AS PRODSTOCK, SUM(OD.QUANTITYORDERED * OD.PRICEEACH) AS REVENUE 
FROM PRODUCTS P, ORDERDETAILS OD, ORDERS O 
WHERE P.PRODUCTCODE=OD.PRODUCTCODE AND OD.ORDERNUMBER=O.ORDERNUMBER
GROUP BY P.PRODUCTNAME 
ORDER BY REVENUE DESC;

-- COUNT OF INVENTORY ORDERED PER YEAR
SELECT EXTRACT(YEAR FROM O.ORDERDATE) AS YEARS, COUNT(OD.PRODUCTCODE) AS PRODNOS 
FROM ORDERS O, ORDERDETAILS OD 
WHERE O.ORDERNUMBER=OD.ORDERNUMBER 
GROUP BY YEARS ORDER BY YEARS;

-- III --
-- COMPARISON OF QUANTITY OF PRODUCTS IN INVENTORY AND ORDERED
SELECT P.PRODUCTNAME, SUM(P.QUANTITYINSTOCK) AS PRODSTOCK, SUM(OD.QUANTITYORDERED) AS ORDERED
FROM PRODUCTS P, ORDERDETAILS OD 
WHERE P.PRODUCTCODE=OD.PRODUCTCODE 
GROUP BY P.PRODUCTNAME 
ORDER BY SUM(OD.QUANTITYORDERED);

-- AVG SELLING PRICE AND PROFIT GENERATED PER PRODUCT
SELECT P.PRODUCTNAME, AVG(OD.PRICEEACH) AS AVGSP, P.BUYPRICE, AVG(OD.PRICEEACH)-P.BUYPRICE AS PROFIT 
FROM ORDERDETAILS OD, PRODUCTS P 
WHERE OD.PRODUCTCODE=P.PRODUCTCODE 
GROUP BY P.BUYPRICE, P.PRODUCTNAME 
ORDER BY PROFIT DESC;